
var levels = [
    {
        "degree": "9 kup",
        "form": "il_jang",
        "name": "Il Jang",
        "type": "Taegeuk",
        "level": "0",
        "pensum": "8. Kup - Taegeuk Il Jang",
    },
    {
        "degree": "8 kup",
        "form": "yi_jang",
        "name": "Yi Jang",
        "type": "Taegeuk",
        "level": "1",
        "pensum": "7. Kup - Taegeuk Yi Jang",
    },
    {
        "degree": "7 kup",
        "form": "sam_jang",
        "name": "Sam Jang",
        "type": "Taegeuk",
        "level": "2",
        "pensum": "6. Kup - Taegeuk Sam Jang",
    },
    {
        "degree": "6 kup",
        "form": "sah_jang",
        "name": "Sah Jang",
        "type": "Taegeuk",
        "level": "3",
        "pensum": "5. Kup - Taegeuk Sah Jang",
    },
    {
        "degree": "5 kup",
        "form": "oh_jang",
        "name": "Oh Jang",
        "type": "Taegeuk",
        "level": "4",
        "pensum": "4. Kup - Taegeuk Oh Jang",
    },
    {
        "degree": "4 kup",
        "form": "yuk_jang",
        "name": "Yuk Jang",
        "type": "Taegeuk",
        "level": "5",
        "pensum": "3. Kup - Taegeuk Yuk Jang",
    },
    {
        "degree": "3 kup",
        "form": "chil_jang",
        "name": "Chil Jang",
        "type": "Taegeuk",
        "level": "6",
        "pensum": "2. Kup - Taegeuk Chil Jang",
    },
    {
        "degree": "2 kup",
        "form": "pal_jang",
        "name": "Pal Jang",
        "type": "Taegeuk",
        "level": "7",
        "pensum": "1. Kup - Taegeuk Pal Jang",
    },
    {
        "degree": "1 kup",
        "form": "koryo",
        "name": "Koryo",
        "type": "Poomsae",
        "level": "8",
        "pensum": "1. Dan - Koryo",
    },
    
]