
var levels = [
    {
        "form": "il_jang",
        "name": "Il Jang",
        "type": "Taegeuk",
        "level": "0",
        "key": "kup_8",
        "pensum": "8. Kup - Gult bælte",
    },
    {
        "form": "yi_jang",
        "name": "Yi Jang",
        "type": "Taegeuk",
        "level": "1",
        "key": "kup_7",
        "pensum": "7. Kup - Grønt bælte",
    },
    {   
        "form": "sam_jang",
        "name": "Sam Jang",
        "type": "Taegeuk",
        "level": "2",
        "key": "kup_6",
        "pensum": "6. Kup - Blåt bælte",
    },
    {
        "form": "sah_jang",
        "name": "Sah Jang",
        "type": "Taegeuk",
        "level": "3",
        "key": "kup_5",
        "pensum": "5. Kup - Blåt bælte med 1 rød snip",
    },
    {
        "form": "oh_jang",
        "name": "Oh Jang",
        "type": "Taegeuk",
        "level": "4",
        "key": "kup_4",
        "pensum": "4. Kup - Rødt bælte",
    },
    {
        "form": "yuk_jang",
        "name": "Yuk Jang",
        "type": "Taegeuk",
        "level": "5",
        "key": "kup_3",
        "pensum": "3. Kup - Rødt bælte med 1 sort snip",
    },
    {
        "form": "chil_jang",
        "name": "Chil Jang",
        "type": "Taegeuk",
        "level": "6",
        "key": "kup_2",
        "pensum": "2. Kup - Rødt bælte med 2 sorte snipper",
    },
    {
        "form": "pal_jang",
        "name": "Pal Jang",
        "type": "Taegeuk",
        "level": "7",
        "key": "kup_1",
        "pensum": "1. Kup - Rødt bælte med 3 sorte snipper",
    },
    {
        "form": "koryo",
        "name": "Koryo",
        "type": "Poomsae",
        "level": "8",
        "key": "dan_1",
        "pensum": "1. Dan - Sort bælte",
    },
    
]